
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu May 05 20:17:38 CEST 2016
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POR = 44;
  public static final int WITH = 20;
  public static final int GE = 41;
  public static final int OUTPUT = 6;
  public static final int PCIERRE = 47;
  public static final int INPUT = 5;
  public static final int INT = 22;
  public static final int SEMICOLON = 49;
  public static final int NOT = 33;
  public static final int AND = 32;
  public static final int IGUAL = 48;
  public static final int LT = 38;
  public static final int CHOOSE = 16;
  public static final int CHOSEN = 18;
  public static final int OR = 31;
  public static final int BOOL = 23;
  public static final int CALL = 19;
  public static final int DIV = 45;
  public static final int NUM = 51;
  public static final int IF = 9;
  public static final int ID = 50;
  public static final int LE = 40;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int METHOD = 4;
  public static final int TRUE = 34;
  public static final int error = 1;
  public static final int MAKES = 7;
  public static final int COMA = 29;
  public static final int MENOS = 43;
  public static final int DONE = 14;
  public static final int NEQ = 37;
  public static final int START = 2;
  public static final int EQ = 36;
  public static final int PAP = 46;
  public static final int ELSE = 11;
  public static final int TO = 26;
  public static final int WHILE = 12;
  public static final int RECEIVING = 21;
  public static final int CONSIDERING = 15;
  public static final int THEN = 10;
  public static final int END = 3;
  public static final int ALL = 25;
  public static final int ARRAYOF = 24;
  public static final int VALUE = 17;
  public static final int AT = 30;
  public static final int FALSE = 35;
  public static final int LLAVEC = 28;
  public static final int GT = 39;
  public static final int LLAVEA = 27;
  public static final int DO = 13;
  public static final int MAS = 42;
}

